### ISSUE TITLE
R CMD check warnings

### ISSUE THREAD

**Issue by hadley** [fmichonneau/phylobase#6] opened 2015-09-30 12:36 UTC
I see

```
checking whether package ‘phylobase’ can be installed ... WARNING
Found the following significant warnings:
  Warning: namespace ‘RCurl’ is not available and has been replaced
  Warning: namespace ‘Matrix’ is not available and has been replaced
See ‘/private/tmp/RtmpKAtbVW/check_cran14a8c2e8e2543/phylobase.Rcheck/00install.out’ for details.
```

**Comment by fmichonneau** [comment] 2015-09-30 18:01
No idea where it's coming from.

phylobase uses neither RCurl nor Matrix. Something wrong with the namespace of a package I depend on?

Will need to investigate further.

**Comment by fmichonneau** [comment] 2015-09-30 18:11
R CMD check complains about the variable `plot.index` possibly indicating a collision but I couldn't find any reference to this object in R sources or metacran...

**Comment by hadley** [comment] 2015-09-30 19:13
Yeah likely to be a dependency of a dependency or something :/

**Comment by fmichonneau** [comment] 2015-09-30 19:18
I can't reproduce it with a fresh library... closing for now.

**Closed by fmichonneau** 2015-09-30 19:18 UTC
